sudo: required
dist: trusty
language: cpp

env:
  global:
    - /usr/local/bin:$PATH

# NOTE: The COMPILER variable is unused. It simply makes the display on
# travis-ci.org more readable.
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - lcov
            - g++-6
            - gdb

      env: COMPILER=g++-6 C_COMPILER=gcc-6       BUILD_TYPE=Coverage
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gdb

      env: COMPILER=g++-6 C_COMPILER=gcc-6       BUILD_TYPE=Debug
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gdb

      env: COMPILER=g++-6 C_COMPILER=gcc-6       BUILD_TYPE=Release
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gdb
      env:
        - COMPILER=clang++ C_COMPILER=clang  BUILD_TYPE=Debug
        - EXTRA_FLAGS="-fsanitize=undefined,address -stdlib=libc++"

install:
  - if [ "${BUILD_TYPE}" == "Coverage" -a "${TRAVIS_OS_NAME}" == "linux" ]; then
      PATH=~/.local/bin:${PATH};
      pip install --user --upgrade pip;
      pip install --user cpp-coveralls;
    fi
    # for coredump
  - ulimit -c unlimited -S
  - cat /proc/sys/kernel/core_pattern

before_script:
    # get RunTest function
    - source test.sh
    - mkdir build && cd build
    - TESTS="queue netpoll fiber mpsc mpmc thread worker scheduler"

script:
    - cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_CXX_FLAGS=${EXTRA_FLAGS} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
    - make
    - for TEST in ${TESTS}; do RunTest test/${TEST}; done

after_success:
  - if [ "${BUILD_TYPE}" == "Coverage" -a "${TRAVIS_OS_NAME}" == "linux" ]; then
      coveralls --include src --include include --gcov-options '\-lp' --root .. --build-root .;
    fi
